---
Name: cookieconsent
---
Broarm\CookieConsent\CookieConsent:
  cookies:
    Necessary:
      local:
        - PHPSESSID
        - CookieConsent
    #Analytics
    #Marketing
    #Preferences

SilverStripe\Control\Director:
  rules:
    acceptAllCookies: PageController

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Broarm\CookieConsent\Extensions\ContentControllerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Broarm\CookieConsent\Extensions\SiteConfigExtension
